apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: test
  name: testdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: test
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        environment: test
    spec:
      containers:
      - image: nginx:1.16
        name: nginx
        
---

apiVersion: v1
kind: Service
metadata:
  name: mwallet-nginx-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 443
  externalIPs:
    - 172.16.20.39
  selector:
    app: mwallet-nginx-app