apiVersion: v1
kind: PersistentVolume
metadata:
  name: mwallet-log-volume
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mwallet-logs
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    path: /home/appadmin/mwallet-logs/
    server: 172.16.20.39
    readOnly: false

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mwallet-logs
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mwallet-logs-volumeclaim
spec:
  storageClassName: mwallet-logs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7Gi